stage:
  global:
    SKIP_HTML_MINIFICATION: true
  build:
    SKIP_SCD: false
    SCD_STRATEGY: "compact"
    SCD_MATRIX:
      "Magento/backend":
        language:
          - en_US
      "Magento/luma":
        language:
          - en_US
          - th_TH
  deploy:
    CRON_CONSUMERS_RUNNER:
      cron_run: true
      max_messages: 1000
      consumers: []
    QUEUE_CONFIGURATION:
      _merge: true
      amqp:
        ssl: true
